### ISSUE TITLE
Duplicate years in wrangling script

### ISSUE THREAD

**Issue by durgesh27** [ZeningQu/World-Bank-Data-by-Indicators#1]
Just wondering why 1960, 1970, 1980, and 1990 are repeated in your wrangling script? It appears to pull in the data twice for each field for these years, essentially doubling the values in all categories in the csvs.

**Comment by light-and-salt** [comment]
Thanks for catching this. It could be a mistake I made

**Comment by jheer** [comment]
It would be nice to fix this, as there are some classes that have still been using these datasets. Thanks!

**Comment by light-and-salt** [comment]
Fixed! Thanks, @durgesh27 @jheer 🎉
